using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PropertyManager.Domain.Entities;

public class Owner
{
    /// <summary>
    /// Unique identifier for the owner. It's auto-generated by the database.
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdOwner { get; set; }

    /// <summary>
    /// Full name of the owner.
    /// </summary>
    
    public string? Name { get; set; }

    /// <summary>
    /// Residential or mailing address of the owner.
    /// </summary>
 
    public string? Address { get; set; }

    /// <summary>
    /// URL or base64 string representing the owner's photo.
    /// </summary>
    public string? Photo { get; set; }

    /// <summary>
    /// Birth date of the owner.
    /// </summary>
    [Display(Name = "Birthday")]
    [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
    [DataType(DataType.Date)]
    public string? Birthday { get; set; }

    /// <summary>
    /// Username or identifier of the user who created this record.
    /// </summary>
    
    public string? CreatedBy { get; set; }

    /// <summary>
    /// Date and time when this record was created.
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// Username or identifier of the user who last updated this record.
    /// </summary>

    public string? UpdatedBy { get; set; }

    /// <summary>
    /// Date and time when this record was last updated.
    /// </summary>
    public DateTime UpdatedDate { get; set; }
}
